Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:80, host:8080 #guest=máquina virtual, #host=máquina física
#     config.vm.network "private_network", ip: "192.168.59.2" #desabilitando pois há bug no virtualbox/vagrant/mac os
    config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)", ip: "192.168.1.226"
    config.vm.provider "virtualbox" do |v|
      v.gui = true
    end
end